Parallel Matrix Multiplication
RuslanBeresnev/Homeworks3 pull request #1
Opened 2022-09-21 20:27 UTC by RuslanBeresnev

2022-10-31 14:48 UTC, yurii-litvinov requested changes

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1.Tests/MatrixGenerationTests.cs
> +        }
Это же два Assert.AreEqual, или, как сейчас модно, Assert.That

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1.Tests/MatrixGenerationTests.cs
> +                    Assert.Fail();
Кто Вас учил так тесты писать? :)

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1.Tests/SingleThreadMatrixMultiplicationTests.cs
> +/// ������������ ������������� ��������� ������
Хм, это в какой кодировке, интересно.

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/GetStatistics.cs
> +namespace Task1;
namespace лучше первой строкой в файле писать

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/GetStatistics.cs
> +internal class GetStatistics
Класс, а называется как действие, а не как сущность

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/GetStatistics.cs
> +    }
```suggestion
    private static float CalculateMathematicalExpectation(float[] values) 
        => values.Average();
```

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/GetStatistics.cs
> +            sumOfSquaredDeviations += (float) Math.Pow(values[i] - mathematicalExpectation, 2);
```suggestion
            sumOfSquaredDeviations += (float)Math.Pow(values[i] - mathematicalExpectation, 2);
```

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/GetStatistics.cs
> +    }
Это тоже можно симпатичнее через LINQ записать

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/GetStatistics.cs
> +        StreamWriter streamWriter = new StreamWriter(statisticsOutputFile);
```suggestion
        using var streamWriter = new StreamWriter(statisticsOutputFile);
```

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/GetStatistics.cs
> +                singleThreadMethodWorkingTimes[launchNumber] = (float) time.Elapsed.TotalSeconds;
Каст пробелом не отделяется

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/MatrixGenerarion.cs
> +        StreamReader streamReader = new StreamReader(fileName);
- Зачем, если у Вас уже есть allLines?
- using var

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/MatrixGenerarion.cs
> +    /// <summary>
```suggestion
    }

    /// <summary>
```

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/MatrixGenerarion.cs
> +        using (StreamWriter streamWriter = new StreamWriter(fileName))
using var. Но интересно, в других методах Вы полностью игнорировали то, что StreamWriter реализует IDisposable. Ладно Вы забыли, но судя пор этой строчке кода, Вы помнили, но не использовали :)

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/MatrixGenerarion.cs
> +        var random = new Random();
Его лучше static-полем сделать, чтобы тыщу раз не создавать. Random всего один нужен

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/Program.cs
> +    static void Main(string[] args)
Говорят, в C# 9 добавили top-level statements, теперь Main писать не нужно

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/Program.cs
> +                GetStatistics.PrintStatistics("../../../Tests Parameters.txt", LAUNCHES_COUNT, "../../../Statistics Output.txt");
Относительные пути надо указывать так, будто всё, что нужно, лежит в рабочей папке, и настраивать рабочую папку в конфигурации запуска в IDE. Иначе если я запущу это дело через dotnet run, оно чёрт знает где будет эти файлы искать.

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/Statistics Output.txt
> +Среднеквадратичное отклонение для однопоточного метода умножения матриц (секунды): 0
Непоказательно.

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/Statistics Output.txt
> +Матожидание для однопоточного метода умножения матриц (секунды): 38,49911
Точность должна быть сопоставима с точностью измерений

2022-10-31 14:48 UTC, yurii-litvinov commented on Задания с 07.09.2022/Task1/Task1/Statistics Output.txt
> +
Что-то это не то, что в условии просили

2022-12-27 09:15 UTC, RuslanBeresnev commented on Задания с 07.09.2022/Task1/Task1/MatrixGenerarion.cs
> +        StreamReader streamReader = new StreamReader(fileName);
Так немного удобнее, понятнее и короче использовать далее

2022-12-28 11:33 UTC, merged