My Thread Pool
RuslanBeresnev/Homeworks3 pull request #3
Opened 2022-10-19 20:39 UTC by RuslanBeresnev

2022-12-26 11:03 UTC, yurii-litvinov requested changes

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1.Tests/MyThreadPoolTests.cs
> +    private MyThreadPool pool = new MyThreadPool(THREADS_COUNT);
```suggestion
    private MyThreadPool pool = new(THREADS_COUNT);
```

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1.Tests/MyThreadPoolTests.cs
> +        Stopwatch time = new Stopwatch();
```suggestion
        Stopwatch time = new();
```

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1.Tests/MyThreadPoolTests.cs
> +        Assert.True(time.Elapsed.TotalMilliseconds < 1100);
Это доказывает, что задач в пуле не меньше заказанного, но не доказывает, что не больше

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1.Tests/MyThreadPoolTests.cs
> +            Assert.AreEqual(i, tasks[i].Result);
Линтер дело говорит, Assert.That прогрессивнее (хотя бы тем, что не надо помнить, какой аргумент expected, какой actual)

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1.Tests/MyThreadPoolTests.cs
> +    }
Ни одного теста на многопоточный доступ к самому тредпулу. А тут может быть много интересного — что будет, если Submit и Shutdown выполнить одновременно, что будет, если Shutdown и ContinueWith...

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1/MyTask.cs
> +    private ManualResetEvent manualResetEvent = new ManualResetEvent(false);
```suggestion
    private ManualResetEvent manualResetEvent = new(false);
```

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1/MyTask.cs
> +public class MyTask<TResult> : IMyTask<TResult>
Этот класс лучше сделать private-вложенным в тредпул, чтобы у внешнего кода не было соблазна вызвать CalculateResult или что-то такое.

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1/MyTask.cs
> +    public MyTask(Func<TResult>? function, MyThreadPool threadPool)
CI недоволен nulklability result-а. И правда, тут ему надо официально разрешить быть null

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1/MyTask.cs
> +    public bool IsComplited { get; set; } = false;
```suggestion
    public bool IsCompleted { get; set; } = false;
```

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1/MyTask.cs
> +            result = value;
Это не нужно, можно было прямо в result писать

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1/MyTask.cs
> +            catchedException = new AggregateException(exception);
Так если было исключение, никто не дёрнет manualResetEvent, и про исключение вызывающий не сможет узнать. Дедлок. И теста на это нет.

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1/MyTask.cs
> +        return threadPool.Submit(() => function(Result));
Нет, так нельзя — если исходная задача длинная, то continuation-ы будут сидеть в пуле и ждать Result, занимая потоки. Так что если, скажем в пуле 10 потоков, мы добавляем задачу, которую считать два часа и 9 Continuation-ов к ней, а потом ещё 9 коротких задач, эти короткие задачи смогут начать считаться только через два часа. В правильном решении Continuation-ы ставятся на пул только по окончании исходной задачи, так что другие задачи могут спокойно пользоваться потоками пула, пока исходная задача считается.

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1/MyThreadPool.cs
> +            autoResetEvent.Set();
autoResetEvent разбудит один поток. И если мы 10 раз вызовем autoResetEvent до переключения потоков, это всё равно, что вызвать его один раз (это просто булевый флажок). Так что задедлочится всё :)

2022-12-26 11:03 UTC, yurii-litvinov commented on Задания с 21.09.2022/Task1/Task1/MyThreadPool.cs
> +            tasksForExecution.Enqueue(newTask.CalculateResult);
Если как раз в это время отработал Shutdown, то задача поставится в очередь, но делать её уже будет некому. При вызове её Result вызывающий задедлочится. Проверка на 67-й строке не поможет, потому что уже на 70-й может отработать Shutdown

2022-12-26 22:04 UTC, RuslanBeresnev commented on Задания с 21.09.2022/Task1/Task1.Tests/MyThreadPoolTests.cs
> +    }
Как раз же есть два последних теста, почему они не подходят ?
В трэдпуле есть только функции добавления задачи и продолжения текущей, и они хотя бы по-минимальному, но тестируют его работу

2022-12-27 00:02 UTC, RuslanBeresnev commented on Задания с 21.09.2022/Task1/Task1/MyTask.cs
> +        return threadPool.Submit(() => function(Result));
А можно это реализовать каким-то образом с использованием async/await ?

2022-12-28 11:32 UTC, merged